name: Docker Image CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5.0.0

      - name: Build Docker Image
        run: |
          docker build -t yoyo7sniper97/quran-app-argo:latest ./CI-app

      - name: List Docker Images
        run: |
          docker images  # Verify the built image

  security_scan:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v5.0.0

      - name: Build Docker Image (for scan)
        run: |
          docker build -t yoyo7sniper97/quran-app-argo:latest ./CI-app

      - name: Scan image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'yoyo7sniper97/quran-app-argo:latest'
          format: 'table'
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
          ignore-unfixed: true
          exit-code: '1'
          timeout: '5m'

  push_image:
    runs-on: ubuntu-latest
    needs: security_scan
    steps:
      - uses: actions/checkout@v5.0.0

      - name: Build Docker Image (for push)
        run: |
          docker build -t yoyo7sniper97/quran-app-argo:latest ./CI-app

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker Image
        run: |
          docker push yoyo7sniper97/quran-app-argo:latest
